# This workflow buils mapmap-server JAR files and publish them. Also upload the artifact so other actions can use it.

name: Build Server JAR

on:
    workflow_call

jobs:
  build-jar:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}/mapmap-server

    - name: Build with Maven
      run: mvn -B package --file mapmap-server/pom.xml -Dmaven.test.skip

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file mapmap-server/pom.xml -s $GITHUB_WORKSPACE/mapmap-server/settings.xml -Dmaven.test.skip
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Rename JAR
      run: |
        mv "mapmap-server/target/mapmap-server-0.0.1-SNAPSHOT.jar" "mapmap-server.jar"

    - name: Cache JAR
      id: cache-jar
      uses: actions/cache@v3
      with:
        path: mapmap-server.jar
        key: mapmap-server-jar
